#!/usr/bin/env python3
"""Generate a .cu file that instantiates the CUB transform kernel for given types.

This is the AOT (ahead-of-time) counterpart to the JIT source generation done
at runtime by cccl_device_binary_transform_build(). The output .cu file is
compiled with ``nvcc -dc -dlto`` to produce LTO-IR, which is then linked at
runtime with operator LTO-IR via nvJitLink.

Usage
-----
Binary transform (two inputs)::

    python gen_transform_kernel.py \\
        --input1-type int --input2-type int --output-type int \\
        --op-name op --op-arity binary \\
        --kernel-name aot_binary_transform \\
        -o kernel.cu

Unary transform (one input)::

    python gen_transform_kernel.py \\
        --input1-type float --output-type float \\
        --op-name op --op-arity unary \\
        --kernel-name aot_unary_transform \\
        -o kernel.cu

The generated file includes CUB headers and defines an ``extern "C"
__global__`` kernel with a fixed, user-chosen name.  The kernel body
replicates the CUB ``transform_kernel`` dispatch logic, calling the
appropriate ``__device__`` implementation function based on the
compile-time policy.  This gives us a known symbol name without needing
NVRTC name lowering or nm/cuobjdump post-processing.
"""

from __future__ import annotations

import argparse
import sys
import textwrap


# Maps CLI type names to C++ type names.
TYPE_MAP = {
    "int8": "int8_t",
    "int16": "int16_t",
    "int32": "int32_t",
    "int": "int32_t",
    "int64": "int64_t",
    "uint8": "uint8_t",
    "uint16": "uint16_t",
    "uint32": "uint32_t",
    "uint64": "uint64_t",
    "float16": "__half",
    "float": "float",
    "float32": "float",
    "double": "double",
    "float64": "double",
}


def _common_header(op_name: str, op_arity: str) -> str:
    """Preamble shared between unary and binary kernels."""
    return textwrap.dedent("""\
        #include <cub/device/dispatch/tuning/tuning_transform.cuh>
        #include <cub/device/dispatch/kernels/kernel_transform.cuh>
    """)


def generate_binary_transform_kernel(
    input1_type: str,
    input2_type: str,
    output_type: str,
    op_name: str,
    kernel_name: str,
) -> str:
    return textwrap.dedent(f"""\
        // Auto-generated by gen_transform_kernel.py — do not edit.
        //
        // Binary transform kernel: ({input1_type}, {input2_type}) -> {output_type}
        // Operator symbol: extern "C" __device__ void {op_name}(const void*, const void*, void*)
        // Kernel entry:    extern "C" __global__ void {kernel_name}(...)

        {_common_header(op_name, "binary")}
        // Operator forward declaration — resolved at link time from operator LTO-IR.
        extern "C" __device__ void {op_name}(const void*, const void*, void*);

        // Operator functor that wraps the extern "C" symbol.
        struct op_wrapper_t {{
          __device__ {output_type} operator()(const {input1_type}& lhs, const {input2_type}& rhs) const {{
            {output_type} result;
            {op_name}(&lhs, &rhs, &result);
            return result;
          }}
        }};

        // Policy selector — same logic the JIT path uses at runtime.
        using PolicySelector = cub::detail::transform::policy_selector_from_types<
          false,  // requires_stable_address
          true,   // dense_output (pointer output)
          ::cuda::std::tuple<{input1_type}*, {input2_type}*>,
          {output_type}*>;
        using OffsetT = long long;

        using namespace cub::detail::transform;

        // Kernel with a fixed extern "C" name.  The body replicates the CUB
        // transform_kernel dispatch so we get a known symbol without mangling.
        extern "C"
        __global__ __launch_bounds__(get_block_threads<PolicySelector>)
        void {kernel_name}(
          _CCCL_GRID_CONSTANT const OffsetT num_items,
          _CCCL_GRID_CONSTANT const int num_elem_per_thread,
          [[maybe_unused]] _CCCL_GRID_CONSTANT const bool can_vectorize,
          _CCCL_GRID_CONSTANT const always_true_predicate pred,
          _CCCL_GRID_CONSTANT const op_wrapper_t f,
          _CCCL_GRID_CONSTANT {output_type}* const out,
          kernel_arg<{input1_type}*> in1,
          kernel_arg<{input2_type}*> in2)
        {{
          _CCCL_ASSERT(blockDim.y == 1 && blockDim.z == 1, "");
          static constexpr transform_policy policy = PolicySelector{{}}(::cuda::arch_id{{CUB_PTX_ARCH / 10}});

          if constexpr (policy.algorithm == Algorithm::prefetch)
          {{
            transform_kernel_prefetch<
              policy.prefetch.block_threads,
              policy.prefetch.prefetch_byte_stride,
              policy.prefetch.unroll_factor>(
                num_items, num_elem_per_thread,
                ::cuda::std::move(pred), ::cuda::std::move(f),
                ::cuda::std::move(out),
                ::cuda::std::move(in1.iterator), ::cuda::std::move(in2.iterator));
          }}
          else if constexpr (policy.algorithm == Algorithm::vectorized)
          {{
            static_assert(::cuda::std::is_same_v<decltype(pred), const always_true_predicate>,
                          "Cannot vectorize transform with a predicate");
            transform_kernel_vectorized<
              policy.vectorized.block_threads,
              policy.vectorized.items_per_thread,
              policy.vectorized.vec_size,
              policy.prefetch.prefetch_byte_stride,
              policy.prefetch.unroll_factor>(
                num_items, num_elem_per_thread, can_vectorize,
                ::cuda::std::move(f), ::cuda::std::move(out),
                ::cuda::std::move(in1.iterator), ::cuda::std::move(in2.iterator));
          }}
          else if constexpr (policy.algorithm == Algorithm::memcpy_async)
          {{
            NV_IF_TARGET(
              NV_PROVIDES_SM_80,
              (transform_kernel_ldgsts<
                policy.async_copy.block_threads,
                policy.async_copy.unroll_factor>(
                  num_items, num_elem_per_thread,
                  ::cuda::std::move(pred), ::cuda::std::move(f),
                  ::cuda::std::move(out),
                  ::cuda::std::move(in1.aligned_ptr), ::cuda::std::move(in2.aligned_ptr));));
          }}
          else if constexpr (policy.algorithm == Algorithm::ublkcp)
          {{
            NV_IF_TARGET(
              NV_PROVIDES_SM_90,
              (transform_kernel_ublkcp<
                policy.async_copy.block_threads,
                policy.async_copy.bulk_copy_alignment,
                policy.async_copy.unroll_factor>(
                  num_items, num_elem_per_thread,
                  ::cuda::std::move(pred), ::cuda::std::move(f),
                  ::cuda::std::move(out),
                  ::cuda::std::move(in1.aligned_ptr), ::cuda::std::move(in2.aligned_ptr));));
          }}
        }}

        using {kernel_name}_func_t = void(
          OffsetT, int, bool, always_true_predicate, op_wrapper_t,
          {output_type}*, kernel_arg<{input1_type}*>, kernel_arg<{input2_type}*>);
        static_assert(::cuda::std::is_same_v<decltype({kernel_name}), {kernel_name}_func_t>,
                      "Kernel signature does not match expected function type");
    """)


def generate_unary_transform_kernel(
    input_type: str,
    output_type: str,
    op_name: str,
    kernel_name: str,
) -> str:
    return textwrap.dedent(f"""\
        // Auto-generated by gen_transform_kernel.py — do not edit.
        //
        // Unary transform kernel: ({input_type}) -> {output_type}
        // Operator symbol: extern "C" __device__ void {op_name}(const void*, void*)
        // Kernel entry:    extern "C" __global__ void {kernel_name}(...)

        {_common_header(op_name, "unary")}
        // Operator forward declaration — resolved at link time from operator LTO-IR.
        extern "C" __device__ void {op_name}(const void*, void*);

        // Operator functor that wraps the extern "C" symbol.
        struct op_wrapper_t {{
          __device__ {output_type} operator()(const {input_type}& arg) const {{
            {output_type} result;
            {op_name}(&arg, &result);
            return result;
          }}
        }};

        // Policy selector — same logic the JIT path uses at runtime.
        using PolicySelector = cub::detail::transform::policy_selector_from_types<
          false,  // requires_stable_address
          true,   // dense_output (pointer output)
          ::cuda::std::tuple<{input_type}*>,
          {output_type}*>;
        using OffsetT = long long;

        using namespace cub::detail::transform;

        extern "C"
        __global__ __launch_bounds__(get_block_threads<PolicySelector>)
        void {kernel_name}(
          _CCCL_GRID_CONSTANT const OffsetT num_items,
          _CCCL_GRID_CONSTANT const int num_elem_per_thread,
          [[maybe_unused]] _CCCL_GRID_CONSTANT const bool can_vectorize,
          _CCCL_GRID_CONSTANT const always_true_predicate pred,
          _CCCL_GRID_CONSTANT const op_wrapper_t f,
          _CCCL_GRID_CONSTANT {output_type}* const out,
          kernel_arg<{input_type}*> in1)
        {{
          _CCCL_ASSERT(blockDim.y == 1 && blockDim.z == 1, "");
          static constexpr transform_policy policy = PolicySelector{{}}(::cuda::arch_id{{CUB_PTX_ARCH / 10}});

          if constexpr (policy.algorithm == Algorithm::prefetch)
          {{
            transform_kernel_prefetch<
              policy.prefetch.block_threads,
              policy.prefetch.prefetch_byte_stride,
              policy.prefetch.unroll_factor>(
                num_items, num_elem_per_thread,
                ::cuda::std::move(pred), ::cuda::std::move(f),
                ::cuda::std::move(out),
                ::cuda::std::move(in1.iterator));
          }}
          else if constexpr (policy.algorithm == Algorithm::vectorized)
          {{
            static_assert(::cuda::std::is_same_v<decltype(pred), const always_true_predicate>,
                          "Cannot vectorize transform with a predicate");
            transform_kernel_vectorized<
              policy.vectorized.block_threads,
              policy.vectorized.items_per_thread,
              policy.vectorized.vec_size,
              policy.prefetch.prefetch_byte_stride,
              policy.prefetch.unroll_factor>(
                num_items, num_elem_per_thread, can_vectorize,
                ::cuda::std::move(f), ::cuda::std::move(out),
                ::cuda::std::move(in1.iterator));
          }}
          else if constexpr (policy.algorithm == Algorithm::memcpy_async)
          {{
            NV_IF_TARGET(
              NV_PROVIDES_SM_80,
              (transform_kernel_ldgsts<
                policy.async_copy.block_threads,
                policy.async_copy.unroll_factor>(
                  num_items, num_elem_per_thread,
                  ::cuda::std::move(pred), ::cuda::std::move(f),
                  ::cuda::std::move(out),
                  ::cuda::std::move(in1.aligned_ptr));));
          }}
          else if constexpr (policy.algorithm == Algorithm::ublkcp)
          {{
            NV_IF_TARGET(
              NV_PROVIDES_SM_90,
              (transform_kernel_ublkcp<
                policy.async_copy.block_threads,
                policy.async_copy.bulk_copy_alignment,
                policy.async_copy.unroll_factor>(
                  num_items, num_elem_per_thread,
                  ::cuda::std::move(pred), ::cuda::std::move(f),
                  ::cuda::std::move(out),
                  ::cuda::std::move(in1.aligned_ptr));));
          }}
        }}

        using {kernel_name}_func_t = void(
          OffsetT, int, bool, always_true_predicate, op_wrapper_t,
          {output_type}*, kernel_arg<{input_type}*>);
        static_assert(::cuda::std::is_same_v<decltype({kernel_name}), {kernel_name}_func_t>,
                      "Kernel signature does not match expected function type");
    """)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a .cu file that AOT-instantiates a CUB transform kernel.",
    )
    parser.add_argument(
        "--input1-type",
        required=True,
        help="C++ type for input 1 (e.g. int, float, double)",
    )
    parser.add_argument(
        "--input2-type", default=None, help="C++ type for input 2 (binary only)"
    )
    parser.add_argument("--output-type", required=True, help="C++ type for output")
    parser.add_argument(
        "--op-name",
        default="op",
        help='extern "C" device function name for the operator',
    )
    parser.add_argument("--op-arity", choices=["unary", "binary"], required=True)
    parser.add_argument(
        "--kernel-name",
        required=True,
        help='Name for the extern "C" __global__ wrapper kernel',
    )
    parser.add_argument(
        "-o", "--output", default="-", help="Output file (default: stdout)"
    )
    args = parser.parse_args()

    def resolve_type(name: str) -> str:
        return TYPE_MAP[name] if name in TYPE_MAP else name

    in1 = resolve_type(args.input1_type)
    out = resolve_type(args.output_type)

    if args.op_arity == "binary":
        if args.input2_type is None:
            parser.error("--input2-type is required for binary transforms")
        in2 = resolve_type(args.input2_type)
        source = generate_binary_transform_kernel(
            in1, in2, out, args.op_name, args.kernel_name
        )
    else:
        if args.input2_type is not None:
            parser.error("--input2-type must not be set for unary transforms")
        source = generate_unary_transform_kernel(
            in1, out, args.op_name, args.kernel_name
        )

    if args.output == "-":
        sys.stdout.write(source)
    else:
        with open(args.output, "w") as f:
            f.write(source)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
